name: Rust Indentation and Linting check

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  lint:
    name: Check Indentation and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check Indentation
        run: cargo fmt --check

      - name: Run Clippy Linter
        run: cargo clippy -- -D warnings
